### ISSUE TITLE
Geogebra embed does not size itself correctly based on its container element size

### ISSUE THREAD

**Issue by LarsTheGlidingSquirrel** [serlo/serlo-editor-for-edusharing#301]
Geogebra plugin is currently deactivated because of this issue. 

Currently, the geogebra embed sizes itself to have height: 0. Even though the container element does not provide a height itself, only the width. 

Steps to reproduce on branch https://github.com/serlo/serlo-editor-for-edusharing/tree/fix-geogebra: 
- Run `yarn dev`
- Open `localhost:8100`
- Create Geogebra element
- Enter some id, for example: nv5wNx9R
- Geogebra embed appears in editor and looks good
- Click 'Speichern'
- Set mayEdit=false in Url to load read-only view (uses "static renderer" here)

Geogebra embed has size 0 here.

**Comment by elbotho** [comment]
the plugin implicitly depends on styling provided by the privacy wrapper in the frontend.
Easiest way would probably be to add the missing wrappers/elements here as well.

**Comment by Entkenntnis** [comment]
The links PR will fix the seizing issue itself.

There are two other issues that are independant of it and also prevent geogebra from displaying properly and in my knowledge happen in the frontend as well:

- The detection of empty media element has an edge case that will not detect geogebra properly and hide it (see screenshot). That's the reason why the plugin is not visible if content is empty
![grafik](https://github.com/serlo/serlo-editor-for-edusharing/assets/13507950/968a34fc-56ca-400f-84e1-40194a90e662)
- You can't add two plugins with the same id - the second one will not load (probably because we are using the id as index internally)
